@host = http://localhost:8000

### USER ENDPOINTS

### Register User
POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "id": 6,
    "username": "logintestPOPUP2",
    "password": "newpassword",
    "email": "newuser@example.com",
    "role": "user"
    
}

### Login User
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}


### Get Users
GET {{host}}/api/users HTTP/1.1

### Get User by ID
GET {{host}}/api/users/4 HTTP/1.1

### GET the latest user id
GET {{host}}/api/users/latest/id HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwMjIwMDgzNiwiZXhwIjoxNzAyMjA0NDM2fQ.p9vnanQF0GlgagXjqO-JdEXhDqAG5fxu3ARDNVbdBs8
### delete User by ID
DELETE {{host}}/api/users/1 HTTP/1.1

### update User by ID
PUT {{host}}/api/users/12 HTTP/1.1
Content-Type: application/json
    
{
    "id": 12,
    "username": "newuser",
    "password": "newpassword",
    "email": "lol@gmail.com",
    "role": "user"
}

### MENU ENDPOINTS

### GET Menu
GET {{host}}/api/menu HTTP/1.1

### GET Menu by ID
GET {{host}}/api/menu/6 HTTP/1.1

### GET Count of FoodItems
GET {{host}}/api/menu/count HTTP/1.1

### GET Menu by Category
GET {{host}}/api/menu/category/salad HTTP/1.1

### POST Menu
POST {{host}}/api/menu/add HTTP/1.1
Content-Type: application/json

{
    "name": "Test Burger",
    "description": "post test food description",
    "price": 22,
    "category": "Burger",
    "image": "post test food image"
}

### PUT Menu by ID
PUT {{host}}/api/menu/4/edit HTTP/1.1
Content-Type: application/json

{
    "name": "Test Burger",
    "description": "put test food description",
    "price": 22,
    "category": "testi",
    "image": "put test food image"
}

### DELETE Menu by ID
DELETE {{host}}/api/menu/7/delete HTTP/1.1


### CART ENDPOINTS

### GET Cart

GET {{host}}/api/cart/7 HTTP/1.1

### GET Cart by User ID

GET {{host}}/api/cart/7 HTTP/1.1

### GET Cart Total by User ID

GET {{host}}/api/cart/total/4 HTTP/1.1

### update the quantity

PATCH {{host}}/api/cart/update HTTP/1.1
Content-Type: application/json

{
    "userId" : 7,
    "foodItemId": 1,
    "newQuantity": 2 
}

### POST Cart

POST {{host}}/api/cart/add HTTP/1.1
Content-Type: application/json

{
    "userId": 1,
    "foodItemId": 1,
    "quantity": 1
}


### ORDER ENDPOINTS

### GET Latest Order ID

GET {{host}}/api/order/latest/orderid HTTP/1.1

### GET ALL ORDERS

GET {{host}}/api/order/all HTTP/1.1

### Chnage order status by ID ( 'pending', 'completed', 'cancelled' )

PUT {{host}}/api/order/status/1 HTTP/1.1
Content-Type: application/json

{
    "newStatus": "pending"
}

### CREATE ORDER

POST {{host}}/api/order/create
Content-Type: application/json

{
    "userId": 7
}

### GET ORDER BY ID

GET {{host}}/api/order/8 HTTP/1.1